### ISSUE TITLE
Should ignore swp files

### ISSUE THREAD

**Issue by jonmast** [iurifq/ctrlp-rails.vim#2]
Currently it returns any hidden files in the directory. This is caused by the use of the find command. Not sure if you would like to introduce an additional dependency but tpope's rails.vim would fix this issue and also detect the rails root. Alternatively you could switch to using vims builtin globbing methods. I would be willing to submit a patch if you could give guidance on what you'd like to see.

**Comment by iurifq** [comment]
Cool, I like the ideas. Honestly I use this plugin just as a fast way to get to the controllers and models. The rest I use tpope's rails.vim. I wanted to make this plugin better by supporting other directory maps(include decorators and make it extensible) but I didn't proceed. Feel free to create a pull request. I'll be glad to review it and merge it.
